version: '3'
services:
  bootstrap_db:
    image: postgres
    container_name: bootstrap_db
    restart: unless-stopped
    ports:
      - '5678:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nano
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: bootstrap
    networks:
     - nano_bootstrap

  nano_bootstrap_overview:
    build: .
    container_name: nano_bootstrap_overview
    restart: unless-stopped
    ports:
     - '127.0.0.1:3044:5000'
    volumes:
    - ./data:/app/data
    networks:
     - nano_bootstrap

networks:
  nano_bootstrap:
    driver: bridge


